### ISSUE TITLE
Cannot find module 'pown-cli'

### ISSUE THREAD

**Issue by Pyr3x** [pownjs/pown-proxy#2]
Installed in two different computers and when attempting to run I get the following error:

Error: Cannot find module 'pown-cli'

**Comment by wongjustin99** [comment]
Also have this issue. Tried also to install the pown package instead. 
 
edit: manually install the "pown-cli"  package

Now, I get an error "Cannot read  property 'address' of null", though

edit1: You need to  specify a port i.e.: `pown-proxy proxy -port=8888`

**Comment by pdparchitect** [comment]
Fixed now in the latest release. Apologies for the inconvenience!
